### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by caarlos0** [Code-Hex/auto-milestone-binder#30]
Hey, thanks for the project!

Found an improvement: every time the action runs, it builds the docker image... it could be faster by building and publishing the docker image to a public registry, and then changing the action.yaml to:

```yaml
runs:
  using: 'docker'
  image: 'docker://owner/image:v1.2.3'
```

Cheers!
